CRS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Reviews/',include('Reviews.urls', namespace='Reviews')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Reviews/urls.py
from django.urls import path,re_path
from . import views

app_name = 'Reviews'
urlpatterns = [

	path('', views.review_list, name='review_list'),
	path('login_user/',views.login_user, name='login_user'),
	path('create_new_user/', views.create_new_user ,name='create_new_user'),
	path('logout_user/',views.logout_user, name='logout_user'),
	path('review/<int:review_id>/', views.review_detail, name='review_detail'),
	path('college/', views.college_list ,name='college_list'),
	path('college/<int:college_id>/add_review/', views.add_review, name='add_review'),
	path('college/<int:college_id>/', views.college_detail, name='college_detail'),
	path('searched/', views.searched, name='searched'),
	path('search/', views.autocomplete_college, name='autocomplete_college'),
	path('add_college/', views.add_college, name='add_college'),
	path('req_query/', views.req_query, name='req_query'),
	path('answer_query/', views.answer_query, name='answer_query'),
	path('submit_query/', views.submit_query, name='submit_query'),
	path('recommend/', views.recommend, name='recommend'),
	path('get_deps/',views.get_deps, name='get_deps'),
]

Reviews/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class College(models.Model):
	name = models.CharField(max_length=100)
	address = models.CharField(max_length=1000, default='N/A')
	pic = models.ImageField(upload_to='', default='def.jpg')
	nirf_rating = models.IntegerField(default=0)

	def __str__(self):
		return self.name


feedback = (
	(1, 'Poor'),
	(2, 'Satisfactory'),
	(3, 'Average'),
	(4, 'Good'),
	(5, 'Excellent'),
)


class Department(models.Model):
	department = models.CharField(max_length=100)
	college = models.ForeignKey(College,on_delete=models.CASCADE)

	def avg_rating(self):
		tot = list(map(lambda x:x.rating,self.review_set.all()))
		avg = 0
		for i in range(len(tot)):
			avg+= tot[i]
		avg/= len(tot)
		return avg

	def avg_p_rating(self):
		tot = list(map(lambda x: x.placement_rate, self.review_set.all()))
		avg = 0
		for i in range(len(tot)):
			avg += int(tot[i])
		avg /= len(tot)
		return avg

	def avg_a_rating(self):
		tot = list(map(lambda x: x.academic_rate, self.review_set.all()))
		avg = 0
		for i in range(len(tot)):
			avg += int(tot[i])
		avg /= len(tot)
		return avg

	def avg_i_rating(self):
		tot = list(map(lambda x: x.infra_rate, self.review_set.all()))
		avg = 0
		for i in range(len(tot)):
			avg += int(tot[i])
		avg /= len(tot)
		return avg

	def __str__(self):
		return self.department



class Review(models.Model):
	college = models.ForeignKey(College, on_delete=models.CASCADE)
	dept = models.ForeignKey(Department, on_delete=models.CASCADE)
	pub_date = models.DateTimeField('Review Publishing Date')
	user_name = models.CharField(max_length=100)
	description = models.CharField(max_length=200)
	academic_rate = models.IntegerField(choices=feedback, default='Other')
	placement_rate = models.IntegerField(choices=feedback, default='Other')
	infra_rate = models.IntegerField(choices=feedback, default='Other')
	rating = models.FloatField()


class PendingQuery(models.Model):
	college = models.ForeignKey(College,on_delete=models.CASCADE)
	qsn = models.CharField(max_length=10000)


class AnsweredQueries(models.Model):
	college = models.ForeignKey(College,on_delete=models.CASCADE)
	qsn = models.CharField(max_length=10000)
	ans = models.CharField(max_length=10000)


type_choices = (
    ('Active Student', 'Active Student'),
    ('Alumni', 'Alumni'),
)


class StudentUser(models.Model):
	user=models.OneToOneField(User,on_delete=models.CASCADE,null=True)
	category = models.CharField(max_length=20, choices=type_choices,default='Other')
	college = models.ForeignKey(College,on_delete=models.CASCADE)
	depart = models.CharField(max_length=20, default='Mechanical')
	dept = models.ForeignKey(Department,on_delete=models.CASCADE)

	def __str__(self):
		return self.user.username


class IndustryUser(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	company = models.CharField(max_length=1000)


class Category(models.Model):
	caste = models.CharField(max_length=10)

	def __str__(self):
		return self.caste


class Cutoff(models.Model):
	college = models.ForeignKey(College, on_delete=models.CASCADE)
	dept = models.CharField(max_length=100)
	caste = models.ForeignKey(Category, on_delete=models.CASCADE)
	score = models.IntegerField(default=0)
	rank = models.IntegerField(default=0)

Reviews/forms.py
from django import forms
from django.forms import ModelForm,PasswordInput, Textarea ,CharField
from Reviews.models import Review,StudentUser, IndustryUser, Department,College
from django.contrib.auth.models import User


class ReviewForm(ModelForm):
    anonymous = forms.BooleanField(required =False)

    class Meta:
        model = Review
        fields = ['anonymous', 'academic_rate', 'placement_rate', 'infra_rate', 'description']
        widgets = {
            'description': Textarea(attrs={'cols': 40, 'rows': 15})
        }


class UserForm(ModelForm):
    class Meta:
        model=User
        fields = ['username', 'password']
        widgets = {
            'password': forms.PasswordInput()
        }


class StudUserForm(ModelForm):
    class Meta:
        model = StudentUser
        fields = ['category', 'college', 'depart']
        widgets = {
            'depart': forms.Select()
        }


class IndUserForm(ModelForm):
    class Meta:
        model = IndustryUser
        fields = ['company']

Reviews/views.py
from django.contrib.auth import authenticate,logout,login
from django.shortcuts import render,get_object_or_404,redirect
from .models import Review,College,PendingQuery,AnsweredQueries, StudentUser, IndustryUser,Department,Cutoff, Category
from django.urls import reverse
from django.http import HttpResponseRedirect,JsonResponse
from .forms import ReviewForm,StudUserForm, UserForm, IndUserForm
import datetime
from textblob import TextBlob


def get_deps(request):
	if request.is_ajax():
		q=request.GET.get('clg', None)
		c=College.objects.filter(name=q)[0]
		queryset = Department.objects.filter(college=c)
		list = []
		for i in queryset:
			if i.department!='TnP':
				list.append(i.department)
		data = {
			'list': list,
		}
		return JsonResponse(data)
	return render(request,'Reviews/create_new_user.html',{})


def recommend(request):
    if request.method == "POST":
        marks=int(request.POST['marks'])
        rank=int(request.POST['rank'])
        dep=request.POST.getlist('dep')
        caste=Category.objects.filter(caste=request.POST['caste'])
        best_clgs=Cutoff.objects.filter(dept__in=dep, caste=caste[0], score__lte=marks, rank__gte=rank).order_by('-score')
        print(best_clgs)
        if len(best_clgs)>5:
            best_clgs=best_clgs[:5]
        return render(request,'Reviews/rec_result.html',{'best_clgs': best_clgs})
    return render(request,'Reviews/recommender.html')


def answer_query(request):
    qsn=request.POST['qstn']
    col=request.POST['colg']
    context={
        'qsn': qsn,
        'col': col,
    }
    return render(request,'Reviews/answer.html',context)


def submit_query(request):
    qsn = request.POST['qstn']
    col = request.POST['colg']
    ans = request.POST['ans']
    aq=AnsweredQueries()
    aq.qsn=qsn
    aq.ans=ans
    pq = PendingQuery.objects.filter(qsn=qsn).delete()
    clge = College.objects.filter(name=col)
    clg = clge[0]
    aq.college=clg
    aq.save()
    deps = Department.objects.filter(college=clg)
    form = ReviewForm()
    user_clg = 'none'
    if not request.user.is_anonymous:
        if StudentUser.objects.filter(user=request.user).exists():
            user_clg = StudentUser.objects.filter(user=request.user)[0].college
        if IndustryUser.objects.filter(user=request.user).exists():
            user_clg = clg.name
    return render(request, 'Reviews/college_detail.html',{'college': clg, 'deps': deps, 'form': form, 'user_clg': user_clg})


def add_college(request):
	college_name=request.POST['clg']
	col = College()
	col.name = college_name
	col.save()
	form = ReviewForm()
	return render(request, 'Reviews/college_detail.html', {'college': col, 'form': form})


def req_query(request):
    qry = request.POST['qry']
    college_nm=request.POST['col']
    clge = College.objects.filter(name=college_nm)
    clg = clge[0]

    pq = PendingQuery()
    pq.college = clg
    pq.qsn = qry
    pq.save()
    deps = Department.objects.filter(college=clg)
    form = ReviewForm()
    user_clg = 'none'
    if not request.user.is_anonymous:
        if StudentUser.objects.filter(user=request.user).exists():
            user_clg = StudentUser.objects.filter(user=request.user)[0].college
        if IndustryUser.objects.filter(user=request.user).exists():
            user_clg = clg.name
    return render(request, 'Reviews/college_detail.html',{'college': clg, 'deps': deps, 'form': form, 'user_clg': user_clg})



def searched(request):
	if request.method == "POST":
		clg_name = request.POST['autocomplete-college']
		if College.objects.filter(name=clg_name).exists():
			clge = College.objects.filter(name=clg_name)
			clg=clge[0]
			deps = Department.objects.filter(college=clg)
			form = ReviewForm()
			user_clg = 'none'
			if not request.user.is_anonymous:
				if StudentUser.objects.filter(user=request.user).exists():
					user_clg = StudentUser.objects.filter(user=request.user)[0].college
				if IndustryUser.objects.filter(user=request.user).exists():
					user_clg = clg.name
			return render(request, 'Reviews/college_detail.html',{'college': clg, 'deps': deps, 'form': form, 'user_clg': user_clg})
		else:
			return render(request, 'Reviews/add_clg.html', {'name': clg_name})
	return render(request, 'Reviews/Search.html')


def autocomplete_college(request):
	if request.is_ajax():
		q=request.GET.get('search', None)
		queryset = College.objects.filter(name__startswith=q)
		list = []
		for i in queryset:
			list.append(i.name)
		data = {
			'list': list,
		}
		return JsonResponse(data)
	return render(request,'Reviews/Search.html',{})


def review_list(request):
	if request.user.is_authenticated==False:
		return render(request, 'Reviews/Search.html')
	else:	
		latest_review_list=Review.objects.order_by('-pub_date')[:9]
		context={'latest_review_list':latest_review_list}
		return render(request,'Reviews/review_list.html',context)


def review_detail(request,review_id):
	review=get_object_or_404(Review,pk=review_id)
	return render(request,'Reviews/review_detail.html',{'review':review})


def college_list(request):
	college_list=College.objects.order_by('-name')
	context={'college_list':college_list}
	return render(request,'Reviews/college_list.html',context)


def college_detail(request,college_id):
	college=get_object_or_404(College,pk=college_id)
	deps=Department.objects.filter(college=college)
	form=ReviewForm()
	user_clg = 'none'
	if not request.user.is_anonymous:
		if StudentUser.objects.filter(user=request.user).exists():
			user_clg = StudentUser.objects.filter(user=request.user)[0].college
		if IndustryUser.objects.filter(user=request.user).exists():
			user_clg = college.name
	return render(request,'Reviews/college_detail.html',{'college':college,'deps':deps, 'form':form, 'user_clg':user_clg})


def add_review(request,college_id):
	college = get_object_or_404(College, pk=college_id)
	deps = Department.objects.filter(college=college)
	form = ReviewForm(request.POST)
	user_clg = 'none'
	if not request.user.is_anonymous:
		if StudentUser.objects.filter(user=request.user).exists():
			user_clg = StudentUser.objects.filter(user=request.user)[0].college
		if IndustryUser.objects.filter(user=request.user).exists():
			user_clg = college.name
	if form.is_valid():
		description = form.cleaned_data['description']
		anonymous=form.cleaned_data['anonymous']
		acad = int(form.cleaned_data['academic_rate'])
		place = int(form.cleaned_data['placement_rate'])
		infra = int(form.cleaned_data['infra_rate'])
		val=TextBlob(description)
		rate=val.sentiment.polarity

		# normalization

		rating = ((rate+1)*5)/2
		print(rate, rating)
		tot_rate = (acad + place + infra + rating)/4
		rating = round(tot_rate, 1)

		review = Review()
		review.college = college
		if StudentUser.objects.filter(user=request.user).exists():
			review.dept = StudentUser.objects.filter(user=request.user)[0].dept
		if IndustryUser.objects.filter(user=request.user).exists():
			review.dept = Department.objects.filter(college=college, department='TnP')[0]
		if anonymous:
			review.user_name = "Anonymous"
		else:
			review.user_name = request.user.username
		review.academic_rate = acad
		review.placement_rate = place
		review.infra_rate = infra
		review.rating = rating
		review.description = description
		review.pub_date = datetime.datetime.now()
		review.save()

		# returning an HttpResponseRedirect prevents data from being posted twice if a user hits the Back button.

		return HttpResponseRedirect(reverse('Reviews:add_review', args=(college.id,)))
	return render(request, 'Reviews/college_detail.html', {'college': college,'deps':deps,'user_clg': user_clg, 'form': form})


def login_user(request):
	if(request.method=="POST"):
		username=request.POST['username']
		password=request.POST['password']
		user=authenticate(username=username,password=password)
		if user is not None:
			login(request,user)
			return redirect('Reviews:review_list')
		else:
			return render(request,'Reviews/login.html')
	return render(request,'Reviews/login.html')


def create_new_user(request):
	Uform = UserForm()
	Sform = StudUserForm()
	Iform = IndUserForm()
	if request.method == "POST":

		Uform = UserForm(data=request.POST)
		Sform = StudUserForm(data=request.POST)
		Iform = IndUserForm(data=request.POST)
		if Uform.is_valid() and Sform.is_valid():
			user = Uform.save(commit=False)
			password = Uform.cleaned_data['password']
			user.set_password(password)
			user.save()
			Sform.save(commit=False)
			stud=StudentUser()
			stud.user=user
			stud.college=Sform.cleaned_data['college']
			stud.category=Sform.cleaned_data['category']
			d=Sform.cleaned_data['depart']
			stud.dept = Department.objects.filter(department=d,college=stud.college)[0]
			print(stud.dept.department,stud.dept.college)
			stud.save()
			login(request, user)
			return redirect('Reviews:review_list')

		if Uform.is_valid() and Iform.is_valid():
			user = Uform.save(commit=False)
			password = Uform.cleaned_data['password']
			user.set_password(password)
			user.save()
			Iform.save(commit=False)
			ind=IndustryUser()
			ind.user=user
			ind.company=Iform.cleaned_data['company']
			ind.save()
			login(request, user)
			return redirect('Reviews:review_list')
	context = {
		"Uform": Uform,
		"Sform": Sform,
		"Iform": Iform,
	}
	return render(request, 'Reviews/create_new_user.html',context)


def logout_user(request):
	logout(request)
	form=StudUserForm(request.POST or None)
	return render(request, 'Reviews/login.html', {"form": form})

Reviews/templates/Reviews/Search.html
<!doctype html>
<html lang="en">
  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Akronim|Stylish" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah|Lato" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'Reviews/css/style.css'%}">

    <title>{% block title %}{%endblock %}</title>
  </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <a class="navbar-brand" href="{% url 'Reviews:searched' %}">College Recommendation System</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


<div class="container">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
	  {% if user.is_authenticated %}
		<li class="nav-item active">
        <a class="nav-link" href="{% url 'Reviews:logout_user' %}">LogOut</a>
		</li>
	  {% else %} 
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Reviews:login_user' %}">LogIn</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Reviews:create_new_user' %}">SignUp</a>
      </li>
	  {% endif %}
    </ul>
  </div>


</nav>
    {% block body %}{%endblock %}

 <div class="card">
  <div class="card-header">
    Search Colleges
  </div>
  <div class="card-body">
     <div class="ui-widget">
       <form action="{% url 'Reviews:searched' %}" method="post">
        {% csrf_token %}
        <label>College: </label>
        <input type ="text" id="autocomplete-college" name="autocomplete-college">
        <br><br><button type="submit">Search</button>
      </form>
  </div>
</div>
   


<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
    $("#autocomplete-college").on('keyup', function(){
        var value = $(this).val();
        $.ajax({
            url: "{% url 'Reviews:autocomplete_college' %}",
            data: {
              'search': value
            },
            dataType: 'json',
            success: function (data) {
              console.log(data.list)
                list = data.list;
                $("#autocomplete-college").autocomplete({
                source: list,
                minLength: 1
                });
            }
        });
    });
  });

    //   keeps same width as box
      jQuery.ui.autocomplete.prototype._resizeMenu = function () {
          var ul = this.menu.element;
          ul.outerWidth(this.element.outerWidth());
        }
</script>

</body>
</html>

Reviews/templates/Reviews/add_clg.html
<html>
<body>

<h2>
Request admin to add {{ name }} to college database??
</h2>
<br><br>
<form action="{% url 'Reviews:add_college'%}" method="post">
    {% csrf_token %}
    <input type="text" name="clg" value="{{ name }}">
    <br><br>
    <button type="submit">Request</button>
</form>

</body>
</html>

Reviews/templates/Reviews/answer.html
<html>
<body>

{% extends 'Reviews/base.html' %}

{% block title %}
    {{ col }}
    <br>
<h4>{{ qsn }}</h4>
{% endblock %}

{% block content %}
<form  action="{% url 'Reviews:submit_query' %}" method="post">
	{% csrf_token %}
    <input type="hidden" value="{{ qsn }}" name="qstn">
	<input type="hidden" value="{{ col }}" name="colg">
    <h4>Answer: </h4>
    <textarea name="ans"></textarea>
<button type="submit">Submit</button>
</form>
{% endblock %}
</body>
</html>

Reviews/templates/Reviews/base.html
<!doctype html>
<html lang="en">
  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Akronim|Stylish" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah|Lato" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'Reviews/css/style.css'%}">
    


<!--head section-->   
  </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <a class="navbar-brand" href="{% url 'Reviews:review_list' %}">College Recommendation System</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="container">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Reviews:review_list' %}">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Reviews:college_list' %}">College List</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Reviews:autocomplete_college' %}">Search</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Reviews:recommend' %}">Recommender</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Reviews:logout_user' %}">LogOut</a>
      </li>
      {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Reviews:login_user' %}">LogIn</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Reviews:create_new_user' %}">Signup</a>
      </li>
      {% endif %}
    </ul>
  </div>


</nav>
 <b><u><h3>{% block title %}{%endblock %}</h3></u></b>
    {% block body %}{%endblock %}
</body>
</html>

Reviews/templates/Reviews/college_detail.html
<html>
<body >
{% extends 'Reviews/base.html' %}
{% block title %}{% endblock %}
{% block body %}
<i><h2>{{ college.name }}</h2></i>
<img src={{ college.pic.url }} height="400" width="1000"/><br>
<h3>Address: {{ college.address }}</h3>
<h4>NIRF RATING: {% if college.nirf_rating > 0 %}
						{{ college.nirf_rating }}
				{% else %}
						N/A
				{% endif %}
</h4>
<hr><br>
<h3>Have a query?Clear them!! </h3>
<br>
<form action="{% url 'Reviews:req_query'%}" method="post">
    {% csrf_token %}
	<textarea name="qry"></textarea><input type="hidden" name="col" value="{{ college.name }}">
    <br>
    <button type="submit">Request</button>
</form>
<br>



<hr>
<div>
    {% for dep in deps %}
       <h3>{{dep }} </h3><br>
           {% if dep.review_set.count > 0	%}
                (Total = {{dep.avg_rating | floatformat}} rated)
                <br>
                <div  class="col-xs-6 col-lg-4">
                    (Placement = {{dep.avg_p_rating | floatformat}})
                
                    (Academics = {{dep.avg_a_rating | floatformat}})
                
                    (Infrastructure = {{dep.avg_i_rating | floatformat}})
                
                </div>
                <div>
                    <br>{{ dep.review_set.count }} Reviews: <br>
                    {% for review in dep.review_set.all %}
                    <div>
                        <br> Description: <em>{{ review.description }}</em>
                        <h5>Rated {{review.rating }}/5 by user {{ review.user_name }}</h5>
                        <h4><a href="{% url 'Reviews:review_detail' review.id%}">
                        Read more..
                        </a></h4>
                    </div>
    {% endfor %}
                </div>
            {% else %}
                <h4>No Reviews for this department yet</h4>
            {% endif %}
    <hr>
    {% endfor %}
</div>

<br>
<hr>



{%  if college.pendingquery_set.all %}
<h3>Pending Queries....</h3><br><br>
{% for qry in college.pendingquery_set.all %}
<h4> {{ qry.qsn }} </h4>
{% if college.name|stringformat:"s" == user_clg|stringformat:"s" %}
<form action="{% url 'Reviews:answer_query'%}" method="post">
	{% csrf_token %}
	<input type="hidden" value="{{ qry.qsn }}" name="qstn">
	<input type="hidden" value="{{ college.name }}" name="colg">
	<button type="submit">Answer</button>
</form>
{% endif %}
		<br>
{% endfor %}
{% else %}
<h4>No Pending Queries for this college yet</h4>
{% endif %}

<br><br>
<hr>
{%  if college.answeredqueries_set.all %}
<h3>Answered Queries....</h3><br><br>
{% for qry in college.answeredqueries_set.all %}
<h4> {{ qry.qsn }} </h4>
<h4> {{ qry.ans }} </h4>
		<br>
{% endfor %}
{% else %}
<h4>No Answered Queries for this college yet</h4>
{% endif %}

<br>
<hr>
{% if college.name|stringformat:"s" == user_clg|stringformat:"s" %}
<h2>Add your review about this college <h2>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'Reviews:add_review' college.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" />
</form>
	{% endif %}

{% endblock %}

</body>
</html>

Reviews/templates/Reviews/create_new_user.html
<html>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
        <script>
            $(document).ready(function(){
                 $('select#id_college').change(function () {
                     var optionSelected = $(this).find("option:selected");
                     var valueSelected  = optionSelected.val();
                     var college_name   = optionSelected.text();
					$.ajax({
					url: "{% url 'Reviews:get_deps' %}",
					data: {'clg': college_name},
					dataType: 'json',
					success: function(data){
						 $("#id_depart option").remove();
						for (var i = data.list.length - 1; i >= 0; i--) {
							$("#id_depart").append('<option>'+ data.list[i] +'</option>');
						};
					}
                 });
            });
        });

        </script>
<body>

<h1>
Sign Up
</h1>
<br><br>
<form class="form-group" role="form" action="" method="post">
	{% csrf_token %}
	<h3><i>For Students</i></h3>
	{{ Uform.as_p }}
	{{ Sform.as_p }}
	<button type="submit">Signup!</button>
</form>	

<br><hr><br>
<form class="form-group" role="form" action="" method="post">
	{% csrf_token %}
	<h3><i>For Industry Experts</i></h3>
	{{ Uform.as_p }}
	{{ Iform.as_p }}
	<button type="submit">Signup!</button>
<br>
<h3>Already have an account?? </h3> 
<form>
	<input type="button" value="Login" onclick="window.location.href='{% url 'Reviews:login_user' %}'"/>
</form>
</body>
</html>